---
- name: Setup CloudberryDB environment
  hosts: gcp_vms
  become: yes
  vars_files:
    - ../vars/main.yml

  roles:
    - role: ../../roles/common
    - role: ../../roles/packages
    - role: ../../roles/users
    - role: ../../roles/sysctl
    - role: ../../roles/cloudberry
